### ISSUE TITLE
Add Google Tag manager to enable web analytics

### ISSUE THREAD

**Issue by vperezb** [aralroca/solbenmoll#78]
**What problem do you want to solve?**

Measure site traffic and optimize campaigns.

**What do you think is the correct solution to this problem?**

Add Google Tag Manager snippets to embed Google Analytics

**Comment by aralroca** [comment]
S'ha de posar dintre la pàgina `_document.js` i ha d'anar com string dintre una clau de React que es diu [`dangerouslySetInnerHTML`](https://reactjs.org/docs/dom-elements.html#dangerouslysetinnerhtml):

![image](https://user-images.githubusercontent.com/13313058/178811820-38475744-1fc7-4934-aa6d-240187a92b66.png)

és l'única manera d'executar JavaScript "normal" fora l'ecosystem de React.
